language: node_js
node_js:
  - "0.12.7"
before_script:
  - npm install -g gulp
  - npm install
  - gulp 
  - gulp start &
sudo: false

script:
  - node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=PhantomJS
  - gulp test:e2e 